driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/wardrobe?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
username=root
password=123456
initialSize=50
maxActive=100
maxWait=60000